### ISSUE TITLE
Use rotary button to set alarmtime

### ISSUE THREAD

**Issue by jpduhen** [adamaze/esphome_volume_knob#2]
Hi adamaze, 
Like this implementation and I would like to use it to set the alarmtime of my wakuplight in HomeAssistant.
I'm no programmer, so I'm struggling with the code to get this working.
How I would like to use the button:
- Long press: enter alarm-setting, hour (turn knob -> hour up/down)
- Short press: toggle between alarm hour/minute set (turning the knob)
- Double press: toggle alarm on/off
- Long press: end alarm setting
All I can find is the "input_datetime.set"-example, but have no clue how to change the hour/minutes this way.
```
- service: input_datetime.set_datetime
  target:
    entity_id: input_datetime.XXX
  data:
    time: "05:30:00"
```
Probably need templating, fiddling with the time:"05:30:00" part, but that's a bit to advanced  and I have no clue how that might look like to get it to work...
Any help appreciated!
